AllCops:
  TargetRubyVersion: 2.7.2
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/ClassVars:
  Enabled: false
  
Lint/UselessAssignment:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics/MethodLength:
  Max: 100

Layout/LineLength:
  Max: 200 

Metrics/AbcSize:
  Max: 100

Metrics/PerceivedComplexity:
  Max: 100

Metrics/BlockLength:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 10

Lint/MissingSuper:
  Enabled: false
